In [60]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train, X_test  = X_train / 255.0, X_test / 255.0
X_train, X_test = X_train.reshape(X_train.shape[0], 28*28), X_test.reshape(X_test.shape[0], 28*28)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 784), (60000,), (10000, 784), (10000,))

In [54]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [61]:
Input = tf.keras.layers.Input(shape=(28*28,))
layer_1 = tf.keras.layers.Dense(128, activation='relu')(Input)
layer_2 = tf.keras.layers.Dense(128, activation='relu')(layer_1)
layer_3 = tf.keras.layers.Dense(10, activation='softmax')(layer_2)  # Softmax or sigmoid -> These are the only ones that have a probability interpretation. The rest of the activation functions are just a transformation of the input data. The softmax function is used for multi-class classification problems, while the sigmoid function is used for binary classification problems.

model = tf.keras.Model(inputs=Input, outputs=layer_3)

model.summary()

Model: "functional_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_12 (InputLayer)     │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 118,282 (462.04 KB)

 Trainable params: 118,282 (462.04 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9308 - loss: 0.2323 - val_accuracy: 0.9632 - val_loss: 0.1135
Epoch 2/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9707 - loss: 0.0982 - val_accuracy: 0.9712 - val_loss: 0.0878
Epoch 3/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9785 - loss: 0.0686 - val_accuracy: 0.9742 - val_loss: 0.0801
Epoch 4/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9843 - loss: 0.0501 - val_accuracy: 0.9743 - val_loss: 0.0862
Epoch 5/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9870 - loss: 0.0404 - val_accuracy: 0.9741 - val_loss: 0.0968
Epoch 6/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9892 - loss: 0.0335 - val_accuracy: 0.9787 - val_loss: 0.0762
Epoch 7/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9913 - loss: 0.0267 - val_accuracy: 0.9752 - val_loss: 0.0873
Epoch 8/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9916 - loss: 0.0249 -

In [57]:
# test
model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_classes[:10], y_test[:10]


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9798 - loss: 0.1490
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


(array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9]),
 array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], dtype=uint8))

In [58]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train, X_test = X_train / 255.0, X_test / 255.0

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [63]:
Input = tf.keras.layers.Input(shape=(28, 28))
layer_1 = tf.keras.layer.Conv2D(32, kernel_size=(3, 3), activation='relu')(Input)
layer_2 = tf.keras.layer.Conv2D(64, kernel_size=(3, 3), activation='relu')(layer_1)
layer_3 = tf.keras.layer.Flatten()(layer_2)
layer_4 = tf.keras.layer.Dense(128, activation='relu')(layer_3)
Output = tf.keras.layer.Dense(10, activation='softmax')(layer_4)

model = tf.keras.Model(inputs=Input, outputs=Output)

AttributeError: module 'tensorflow.keras' has no attribute 'layer'